[package]
name = "lore-credential"
edition = "2024"
version.workspace = true
publish = false

[lib]
name = "lore_credential"
test = false

[dependencies]
base64 = { workspace = true }
jsonwebtoken = { workspace = true }
keyring = { workspace = true }
lore-base = { workspace = true }
lore-error-set = { workspace = true }
ring = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
url = { workspace = true }

[dev-dependencies]
lore-credential = { workspace = true, features = ["test-util"] }

[features]
test-util = []
trace_log = ["lore-base/trace_log"]

[target.'cfg(target_family = "windows")'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem"] }

[lints]
workspace = true
