// This file is @generated by prost-build.
/// Per-service endpoint URLs. An empty string means "no override for this
/// service"; clients fall back to the URL they were configured with. The
/// server stores whatever the operator configured verbatim; URLs are
/// expected to be fully-qualified (`scheme://host[:port][/path]`).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Endpoint {
    /// Authentication / authorisation token-exchange endpoint.
    #[prost(string, tag = "1")]
    pub auth_url: ::prost::alloc::string::String,
    /// Repository-management service endpoint.
    #[prost(string, tag = "2")]
    pub repository_url: ::prost::alloc::string::String,
    /// Storage service endpoint.
    #[prost(string, tag = "3")]
    pub storage_url: ::prost::alloc::string::String,
    /// Revision-graph service endpoint.
    #[prost(string, tag = "4")]
    pub revision_url: ::prost::alloc::string::String,
    /// Lock service endpoint.
    #[prost(string, tag = "5")]
    pub lock_url: ::prost::alloc::string::String,
    /// Notification service endpoint.
    #[prost(string, tag = "6")]
    pub notification_url: ::prost::alloc::string::String,
    /// User directory endpoint: resolves user IDs to display names and back.
    /// Falls back to `auth_url` if empty.
    #[prost(string, tag = "7")]
    pub user_url: ::prost::alloc::string::String,
}
impl ::prost::Name for Endpoint {
    const NAME: &'static str = "Endpoint";
    const PACKAGE: &'static str = "lore.environment.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.environment.v1.Endpoint".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.environment.v1.Endpoint".into()
    }
}
/// Server-tunable configuration knobs returned alongside the endpoint
/// directory.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    /// Maximum number of addresses the server accepts in a single
    /// `StorageService.Query` batch. `0` means "use the client default".
    #[prost(uint32, tag = "1")]
    pub max_query_batch: u32,
    /// Preferred compression mode for new payloads. Unset means the server
    /// has no opinion; the client's local configuration wins.
    #[prost(enumeration = "CompressionMode", optional, tag = "2")]
    pub compression_mode: ::core::option::Option<i32>,
}
impl ::prost::Name for Config {
    const NAME: &'static str = "Config";
    const PACKAGE: &'static str = "lore.environment.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.environment.v1.Config".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.environment.v1.Config".into()
    }
}
/// Composite environment record returned by EnvironmentGet.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Environment {
    /// Per-service endpoint URLs.
    #[prost(message, optional, tag = "1")]
    pub endpoint: ::core::option::Option<Endpoint>,
    /// Server-tunable configuration knobs.
    #[prost(message, optional, tag = "2")]
    pub config: ::core::option::Option<Config>,
}
impl ::prost::Name for Environment {
    const NAME: &'static str = "Environment";
    const PACKAGE: &'static str = "lore.environment.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.environment.v1.Environment".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.environment.v1.Environment".into()
    }
}
/// Empty request envelope (the call has no parameters).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentGetRequest {}
impl ::prost::Name for EnvironmentGetRequest {
    const NAME: &'static str = "EnvironmentGetRequest";
    const PACKAGE: &'static str = "lore.environment.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.environment.v1.EnvironmentGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.environment.v1.EnvironmentGetRequest".into()
    }
}
/// Response carrying the environment record.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentGetResponse {
    /// The server's current environment configuration.
    #[prost(message, optional, tag = "1")]
    pub environment: ::core::option::Option<Environment>,
}
impl ::prost::Name for EnvironmentGetResponse {
    const NAME: &'static str = "EnvironmentGetResponse";
    const PACKAGE: &'static str = "lore.environment.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.environment.v1.EnvironmentGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.environment.v1.EnvironmentGetResponse".into()
    }
}
/// Compression algorithm to use when storing payloads.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompressionMode {
    /// Server has no opinion; the client picks based on its own configuration.
    NotSpecified = 0,
    /// Disable compression entirely.
    NoCompression = 1,
    Lz4 = 2,
    Oodle = 3,
    Zstd = 4,
}
impl CompressionMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotSpecified => "NOT_SPECIFIED",
            Self::NoCompression => "NO_COMPRESSION",
            Self::Lz4 => "LZ4",
            Self::Oodle => "OODLE",
            Self::Zstd => "ZSTD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOT_SPECIFIED" => Some(Self::NotSpecified),
            "NO_COMPRESSION" => Some(Self::NoCompression),
            "LZ4" => Some(Self::Lz4),
            "OODLE" => Some(Self::Oodle),
            "ZSTD" => Some(Self::Zstd),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod environment_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Server-side environment discovery service. Clients call this once during
    /// connection setup to learn which auxiliary endpoints (storage, revision,
    /// lock, notification, ...) live at which URLs and to read server-tunable
    /// configuration (compression mode, query batch size). The service is
    /// unauthenticated — it does not depend on any per-repository state.
    #[derive(Debug, Clone)]
    pub struct EnvironmentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EnvironmentServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EnvironmentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EnvironmentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EnvironmentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Fetch the server's current environment configuration. Servers in
        /// maintenance mode respond with `Unavailable` and a message containing
        /// "maintenance".
        pub async fn environment_get(
            &mut self,
            request: impl tonic::IntoRequest<super::EnvironmentGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnvironmentGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.environment.v1.EnvironmentService/EnvironmentGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "lore.environment.v1.EnvironmentService",
                        "EnvironmentGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod environment_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EnvironmentServiceServer.
    #[async_trait]
    pub trait EnvironmentService: std::marker::Send + std::marker::Sync + 'static {
        /// Fetch the server's current environment configuration. Servers in
        /// maintenance mode respond with `Unavailable` and a message containing
        /// "maintenance".
        async fn environment_get(
            &self,
            request: tonic::Request<super::EnvironmentGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnvironmentGetResponse>,
            tonic::Status,
        >;
    }
    /// Server-side environment discovery service. Clients call this once during
    /// connection setup to learn which auxiliary endpoints (storage, revision,
    /// lock, notification, ...) live at which URLs and to read server-tunable
    /// configuration (compression mode, query batch size). The service is
    /// unauthenticated — it does not depend on any per-repository state.
    #[derive(Debug)]
    pub struct EnvironmentServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EnvironmentServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for EnvironmentServiceServer<T>
    where
        T: EnvironmentService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.environment.v1.EnvironmentService/EnvironmentGet" => {
                    #[allow(non_camel_case_types)]
                    struct EnvironmentGetSvc<T: EnvironmentService>(pub Arc<T>);
                    impl<
                        T: EnvironmentService,
                    > tonic::server::UnaryService<super::EnvironmentGetRequest>
                    for EnvironmentGetSvc<T> {
                        type Response = super::EnvironmentGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EnvironmentGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EnvironmentService>::environment_get(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EnvironmentGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EnvironmentServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.environment.v1.EnvironmentService";
    impl<T> tonic::server::NamedService for EnvironmentServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
