// This file is @generated by prost-build.
/// A user as the directory knows them.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    /// The durable user identifier, the value Lore records as a repository's
    /// `creator`, a revision's author or a lock's `owner`.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// The name shown for the user.
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    /// The login name, unique among the directory's users. In OIDC tokens
    /// this is `preferred_username`. Empty when the directory has none.
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
}
impl ::prost::Name for User {
    const NAME: &'static str = "User";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.User".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.User".into()
    }
}
/// Request to resolve user IDs within a partition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserGetRequest {
    /// The partition the caller is working in, so a directory that
    /// scopes user visibility by partition can restrict its answer.
    /// A directory that does not scope by partition ignores it.
    #[prost(bytes = "bytes", tag = "1")]
    pub partition: ::prost::bytes::Bytes,
    /// The user IDs to resolve.
    #[prost(string, repeated, tag = "2")]
    pub id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for UserGetRequest {
    const NAME: &'static str = "UserGetRequest";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.UserGetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.UserGetRequest".into()
    }
}
/// Response carrying the users known by the directory.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserGetResponse {
    /// One entry per requested ID the directory knows, each carrying its `id`,
    /// so the order carries no meaning. Unknown IDs are absent.
    #[prost(message, repeated, tag = "1")]
    pub user: ::prost::alloc::vec::Vec<User>,
}
impl ::prost::Name for UserGetResponse {
    const NAME: &'static str = "UserGetResponse";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.UserGetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.UserGetResponse".into()
    }
}
/// Request to find users by name within a partition.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserFindRequest {
    /// The partition the caller is working in. See `UserGetRequest`.
    #[prost(bytes = "bytes", tag = "1")]
    pub partition: ::prost::bytes::Bytes,
    /// Which field the name is matched against, exactly.
    #[prost(oneof = "user_find_request::Query", tags = "2, 3")]
    pub query: ::core::option::Option<user_find_request::Query>,
}
/// Nested message and enum types in `UserFindRequest`.
pub mod user_find_request {
    /// Which field the name is matched against, exactly.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Query {
        /// `User.username`. Unique, so at most one user matches.
        #[prost(string, tag = "2")]
        Username(::prost::alloc::string::String),
        /// `User.display_name`. Not unique, so several users may match.
        #[prost(string, tag = "3")]
        DisplayName(::prost::alloc::string::String),
    }
}
impl ::prost::Name for UserFindRequest {
    const NAME: &'static str = "UserFindRequest";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.UserFindRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.UserFindRequest".into()
    }
}
/// Response carrying every user the query matched.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserFindResponse {
    /// The matching users. Empty when none matches.
    #[prost(message, repeated, tag = "1")]
    pub user: ::prost::alloc::vec::Vec<User>,
}
impl ::prost::Name for UserFindResponse {
    const NAME: &'static str = "UserFindResponse";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.UserFindResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.UserFindResponse".into()
    }
}
/// Request to stream the caller's partitions. The caller ID is read from
/// the token.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartitionListRequest {}
impl ::prost::Name for PartitionListRequest {
    const NAME: &'static str = "PartitionListRequest";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.PartitionListRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.PartitionListRequest".into()
    }
}
/// One-per-stream-message response carrying a single partition the bearer
/// holds permissions on.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartitionListResponse {
    /// The partition id.
    #[prost(bytes = "bytes", tag = "1")]
    pub partition: ::prost::bytes::Bytes,
    /// The permission names the bearer holds on the partition.
    #[prost(string, repeated, tag = "2")]
    pub permission: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for PartitionListResponse {
    const NAME: &'static str = "PartitionListResponse";
    const PACKAGE: &'static str = "lore.user.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "lore.user.v1.PartitionListResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/lore.user.v1.PartitionListResponse".into()
    }
}
/// Generated client implementations.
pub mod user_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// User directory. Clients call this service to resolve user names/ids and
    /// user partition lists.
    #[derive(Debug, Clone)]
    pub struct UserServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UserServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UserServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UserServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UserServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Resolve user IDs to users. IDs the directory does not know are omitted
        /// from the answer rather than reported as errors.
        pub async fn user_get(
            &mut self,
            request: impl tonic::IntoRequest<super::UserGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.user.v1.UserService/UserGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.user.v1.UserService", "UserGet"));
            self.inner.unary(req, path, codec).await
        }
        /// Find the users whose username or display name equals a given name.
        pub async fn user_find(
            &mut self,
            request: impl tonic::IntoRequest<super::UserFindRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserFindResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.user.v1.UserService/UserFind",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.user.v1.UserService", "UserFind"));
            self.inner.unary(req, path, codec).await
        }
        /// Stream the partitions the bearer holds permissions on, one per message,
        /// with the permissions held on each. The Lore server drives
        /// `RepositoryList` from this.
        pub async fn partition_list(
            &mut self,
            request: impl tonic::IntoRequest<super::PartitionListRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PartitionListResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/lore.user.v1.UserService/PartitionList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("lore.user.v1.UserService", "PartitionList"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod user_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with UserServiceServer.
    #[async_trait]
    pub trait UserService: std::marker::Send + std::marker::Sync + 'static {
        /// Resolve user IDs to users. IDs the directory does not know are omitted
        /// from the answer rather than reported as errors.
        async fn user_get(
            &self,
            request: tonic::Request<super::UserGetRequest>,
        ) -> std::result::Result<tonic::Response<super::UserGetResponse>, tonic::Status>;
        /// Find the users whose username or display name equals a given name.
        async fn user_find(
            &self,
            request: tonic::Request<super::UserFindRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UserFindResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the PartitionList method.
        type PartitionListStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PartitionListResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream the partitions the bearer holds permissions on, one per message,
        /// with the permissions held on each. The Lore server drives
        /// `RepositoryList` from this.
        async fn partition_list(
            &self,
            request: tonic::Request<super::PartitionListRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::PartitionListStream>,
            tonic::Status,
        >;
    }
    /// User directory. Clients call this service to resolve user names/ids and
    /// user partition lists.
    #[derive(Debug)]
    pub struct UserServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> UserServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for UserServiceServer<T>
    where
        T: UserService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/lore.user.v1.UserService/UserGet" => {
                    #[allow(non_camel_case_types)]
                    struct UserGetSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::UserGetRequest>
                    for UserGetSvc<T> {
                        type Response = super::UserGetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserGetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::user_get(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UserGetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.user.v1.UserService/UserFind" => {
                    #[allow(non_camel_case_types)]
                    struct UserFindSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::UserFindRequest>
                    for UserFindSvc<T> {
                        type Response = super::UserFindResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UserFindRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::user_find(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UserFindSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/lore.user.v1.UserService/PartitionList" => {
                    #[allow(non_camel_case_types)]
                    struct PartitionListSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::ServerStreamingService<super::PartitionListRequest>
                    for PartitionListSvc<T> {
                        type Response = super::PartitionListResponse;
                        type ResponseStream = T::PartitionListStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PartitionListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::partition_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PartitionListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for UserServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "lore.user.v1.UserService";
    impl<T> tonic::server::NamedService for UserServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
