[package]
name = "lore"
edition = "2024"
version.workspace = true
publish = false

[lib]
name = "lore"

[dependencies]
bitcode = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }
lore-base = { workspace = true }
lore-io = { workspace = true }
lore-storage = { workspace = true }
lore-revision = { workspace = true }
lore-credential = { workspace = true }
lore-transport = { workspace = true }
lore-error-set = { workspace = true }
lore-macro = { workspace = true }
lore-notification = { workspace = true }

[target.'cfg(target_family = "windows")'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_System_Console",
] }

[features]
default = []
oodle = ["lore-revision/oodle"]
swfs = ["lore-revision/swfs"]

[dev-dependencies]
ctor = { workspace = true }
lore-base = { workspace = true, features = ["test-util"] }
rand = { workspace = true }
serial_test = { workspace = true }
