// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// ============================================================================
// This file is automatically generated by build.rs during compilation.
// Any manual changes will be overwritten on the next build.
//
// To add a new plugin/hook:
// 1. Create a new .rs file in the appropriate directory (plugins/ or hooks/)
// 2. Implement the required traits and register() function
// 3. Run `cargo build` - this file will be regenerated automatically
// ============================================================================

//! Hook infrastructure for Lore Server modularization.
//!
//! This module provides an event-driven hook system that allows code to be
//! executed at specific points in the server lifecycle without modifying
//! core handlers. Hooks can:
//!
//! - Read operation context (repository, branch, user, revision)
//! - Mutate context data for downstream hooks and handlers
//! - Veto operations by returning errors with semantic status codes
//!
//! # Architecture
//!
//! The hook system consists of four main components:
//!
//! 1. **Traits** ([`traits`]) - Core trait definitions ([`Hook`], [`HookFactory`])
//! 2. **Context** ([`context`]) - Operation context passed to hooks ([`HookContext`])
//! 3. **Registry** ([`registry`]) - Factory registration and hook creation ([`HookRegistry`])
//! 4. **Dispatcher** ([`dispatch`]) - Hook execution with isolation ([`HookDispatcher`])
//!
//! # Two-Phase Execution Model
//!
//! The hook system supports a two-phase execution model:
//!
//! 1. **Pre-handler** (synchronous): Called BEFORE the operation
//!    - Can read/modify context
//!    - Can veto/reject by returning `Err(HookError::Rejected)`
//!    - Subject to timeout (default 200ms)
//!    - Panics are caught and isolated
//!
//! 2. **Post-handler** (asynchronous): Called AFTER the operation
//!    - Spawned in separate tokio task
//!    - Does not block the response
//!    - Errors are logged but not propagated
//!
//! # Hook Points
//!
//! Hooks can be triggered at:
//!
//! - [`HookPoint::BranchPush`] - When a branch is pushed to
//! - [`HookPoint::BranchCreate`] - When a new branch is created
//! - [`HookPoint::BranchDelete`] - When a branch is deleted
//! - [`HookPoint::RepositoryCreate`] - When a new repository is created
//! - [`HookPoint::Obliterate`] - When data is obliterated
//!
//! # Status Codes
//!
//! Hooks can reject operations with semantic status codes via [`StatusCode`]:
//!
//! - [`StatusCode::PermissionDenied`] - Policy or authorization violations
//! - [`StatusCode::FailedPrecondition`] - General business rule violations
//! - [`StatusCode::ResourceExhausted`] - Rate limiting, quota exceeded
//! - [`StatusCode::InvalidArgument`] - Validation failures
//! - [`StatusCode::Aborted`] - Conflict/concurrency issues
//!
//! # Usage
//!
//! ## Registering Hooks
//!
//! Hooks are registered at application startup via the auto-generated
//! `register_all_hooks()` function. A [`HookRegistrationContext`] provides
//! runtime dependencies (e.g., notification sender) to hook factories:
//!
//! ```no_run
//! use lore_server::hooks::{HookRegistry, HookRegistrationContext};
//!
//! # fn example(ctx: &HookRegistrationContext) {
//! let mut registry = HookRegistry::new();
//! lore_server::hooks::register_all_hooks(&mut registry, &ctx);
//!
//! // List registered hooks (populated by build.rs auto-discovery)
//! let hooks = registry.list_hooks();
//! # }
//! ```
//!
//! ## Creating Enabled Hooks
//!
//! Enabled hooks are created based on configuration:
//!
//! ```
//! use lore_server::hooks::{HookRegistry, HookSettings};
//! use std::collections::HashMap;
//!
//! let registry = HookRegistry::new();
//! let settings: HashMap<String, HookSettings> = HashMap::new();
//! let enabled_hooks = registry.create_enabled_hooks(&settings).unwrap();
//! // enabled_hooks is empty because no hooks are registered
//! ```
//!
//! ## Creating the Dispatcher
//!
//! The dispatcher executes hooks at runtime:
//!
//! ```
//! use lore_server::hooks::HookDispatcher;
//! use std::time::Duration;
//!
//! // Create from enabled hooks with default timeouts
//! let enabled_hooks = vec![];
//! let dispatcher = HookDispatcher::from_hooks_default(enabled_hooks);
//!
//! // Or create an empty dispatcher directly
//! let dispatcher = HookDispatcher::empty();
//! ```
//!
//! ## Dispatching Hooks (Two-Phase)
//!
//! Hooks are dispatched from request handlers using the two-phase model:
//!
//! ```
//! use lore_server::hooks::{HookContext, HookDispatcher, HookPoint};
//! use lore_revision::lore::{BranchId, RepositoryId};
//!
//! // Create context for the operation
//! let ctx = HookContext::builder()
//!     .correlation_id("correlation-123")
//!     .hook_point(HookPoint::BranchPush)
//!     .repository(RepositoryId::default())
//!     .branch(BranchId::default())
//!     .user("user_id")
//!     .build();
//!
//! // Create dispatcher
//! let dispatcher = HookDispatcher::empty();
//!
//! // Phase 1: Dispatch pre-handlers (synchronous, can veto)
//! // dispatcher.dispatch_pre(HookPoint::BranchPush, &ctx)?;
//!
//! // ... perform the actual operation ...
//!
//! // Phase 2: Spawn post-handlers (asynchronous, non-blocking)
//! // dispatcher.spawn_post(HookPoint::BranchPush, ctx);
//! ```
//!
//! # Implementing Hooks
//!
//! To create a new hook:
//!
//! 1. Create a new file in `src/hooks/` (e.g., `my_hook.rs`)
//! 2. Implement the [`Hook`] trait with `pre_handler()` and/or `post_handler()`
//! 3. Implement a [`HookFactory`] for your hook
//! 4. Add a `register()` function to register the factory
//!
//! ```
//! // src/hooks/my_hook.rs
//! use async_trait::async_trait;
//! use lore_server::hooks::{
//!     Hook, HookContext, HookError, HookFactory, HookPoint, HookRegistrationContext, HookRegistry, StatusCode
//! };
//!
//! struct MyHook {
//!     config_value: String,
//! }
//!
//! #[async_trait]
//! impl Hook for MyHook {
//!     fn name(&self) -> &'static str {
//!         "my_hook"
//!     }
//!
//!     fn hook_points(&self) -> &'static [HookPoint] {
//!         &[HookPoint::BranchPush]
//!     }
//!
//!     fn pre_handler(&self, ctx: &HookContext) -> Result<(), HookError> {
//!         // Validate before operation (can reject)
//!         if ctx.user().map_or(false, |u| u.starts_with("blocked_")) {
//!             return Err(HookError::rejected(
//!                 self.name(),
//!                 "User is blocked",
//!                 StatusCode::PermissionDenied,
//!             ));
//!         }
//!         Ok(())
//!     }
//!
//!     async fn post_handler(&self, ctx: &HookContext) -> Result<(), HookError> {
//!         // Audit logging after operation (non-blocking)
//!         println!("MyHook post-handler: {}", ctx.correlation_id());
//!         Ok(())
//!     }
//! }
//!
//! struct MyHookFactory;
//!
//! impl HookFactory for MyHookFactory {
//!     fn name(&self) -> &'static str {
//!         "my_hook"
//!     }
//!
//!     fn create(&self, config: &toml::Value) -> Result<Box<dyn Hook>, HookError> {
//!         // Parse config and create hook
//!         let config_value = config
//!             .get("value")
//!             .and_then(|v| v.as_str())
//!             .unwrap_or("default")
//!             .to_string();
//!         Ok(Box::new(MyHook { config_value }))
//!     }
//! }
//!
//! pub fn register(registry: &mut HookRegistry, _ctx: &HookRegistrationContext) {
//!     registry.register_hook(Box::new(MyHookFactory));
//! }
//!
//! # fn main() {
//! // Test the factory
//! let factory = MyHookFactory;
//! let config = toml::Value::Table(toml::map::Map::new());
//! let hook = factory.create(&config).unwrap();
//! assert_eq!(hook.name(), "my_hook");
//! # }
//! ```
//!
//! # Error Handling
//!
//! Hook errors are categorized as:
//!
//! - [`HookError::Rejected`] - Hook explicitly rejected/vetoed the operation
//! - [`HookError::ExecutionFailed`] - Hook returned an error (may veto operation)
//! - [`HookError::Timeout`] - Hook exceeded timeout (default 200ms for pre, 30s for post)
//! - [`HookError::Panic`] - Hook panicked (caught and isolated)
//! - [`HookError::ConfigError`] - Hook configuration is invalid
//! - [`HookError::InitError`] - Hook initialization failed
//!
//! All errors include the hook name and relevant context for debugging.
//! Errors are logged with correlation IDs for audit trails.

pub mod context;
pub mod dispatch;
pub mod registry;
pub mod traits;

// Re-export commonly used items at the module level
pub use context::HookContext;
pub use context::HookContextBuilder;
pub use dispatch::DEFAULT_POST_HANDLER_TIMEOUT;
pub use dispatch::DEFAULT_PRE_HANDLER_TIMEOUT;
pub use dispatch::HookDispatcher;
pub use registry::HookRegistrationContext;
pub use registry::HookRegistry;
pub use registry::HookSettings;
pub use traits::Hook;
pub use traits::HookError;
pub use traits::HookFactory;
pub use traits::HookPoint;
pub use traits::HookResponse;
pub use traits::StatusCode;

/// Registers all compiled-in hooks with the registry.
///
/// This function is auto-generated by `build.rs` and calls each hook's
/// `register()` function to register its factory with the registry.
///
/// # Arguments
///
/// * `registry` - The hook registry to register hooks with
/// * `ctx` - Registration context providing runtime dependencies for hook factories
pub fn register_all_hooks(registry: &mut HookRegistry, ctx: &HookRegistrationContext) {
    // No hooks discovered - registry will be empty
    let _ = (registry, ctx); // Suppress unused variable warnings
}
