// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT

//! Conformance of the filter against gitignore.
//!
//! **Every expectation in this file is ground truth taken from git.** The table
//! in `data/gitignore_ground_truth.rs` was generated by
//! `scripts/test/gitignore_matrix.py`, which runs each pattern set through a
//! real throwaway git repository over a real tree and records which paths
//! survive `git status --porcelain -uall`. Nothing here is a hand-written
//! reading of the gitignore spec, because a reading is exactly the thing that
//! has been wrong before: `foo/*` does not match `foo/bar/hello.c`, yet git
//! still ignores that file, because it pruned at `foo/bar`.
//!
//! gitignore is the standard lore follows. Lore departs from it in four places,
//! each asserted below rather than merely described:
//!
//! 1. **Re-inclusion below an excluded directory.** Git prunes at an excluded
//!    directory and its documentation states that re-including anything below
//!    one is impossible. Lore descends when a rule could re-include something
//!    deeper, which is the whole point of the view filter.
//! 2. **A path re-inclusion covers its subtree.** `!d/e` re-includes everything
//!    under `d/e`; git's `!d/e` matches the single path `d/e`. Without this a
//!    sparse view built from `**` plus a list of paths would return only the
//!    directories named and none of their contents.
//!
//!    Both of the above can only ever make lore include *more* than git, never
//!    less. [`gitignore_conformance`] asserts that: it fails on any path git
//!    keeps and lore drops, and on any extra path that is not explained by one
//!    of these two.
//! 3. **Unanchored multi-component inclusions are refused.** See
//!    [`unanchored_multi_component_inclusion_is_refused`].
//! 4. **Case-insensitivity.** Git is case-sensitive by default; lore is not.
//!    See [`matching_is_case_insensitive`].

use std::collections::BTreeSet;

use lore_revision::filter::FilterInstance;
use lore_revision::filter::FilterState;
use lore_revision::filter::FilterStates;
use lore_revision::util::path::RelativePath;

#[path = "data/gitignore_ground_truth.rs"]
mod ground_truth;

use ground_truth::CASES;
use ground_truth::DIRS;
use ground_truth::FILES;

fn path(value: &str) -> RelativePath {
    RelativePath::new_from_initial_path(value).expect("valid relative path")
}

/// Builds a filter from `.gitignore`-style lines.
///
/// Returns `None` when lore refuses a rule outright, which happens only for an
/// unanchored multi-component inclusion -- see
/// [`unanchored_multi_component_inclusion_is_refused`].
fn build(patterns: &[&str]) -> Option<FilterInstance> {
    let mut filter = FilterInstance::default();
    for pattern in patterns {
        if let Some(rest) = pattern.strip_prefix('!') {
            filter.add_inclusion(rest).ok()?;
        } else {
            filter.add_exclusion(pattern).expect("exclusion");
        }
    }
    Some(filter)
}

/// Children of `dir` in `tree`, split into subdirectories and files.
fn children(tree: &[&str], dir: &str) -> (Vec<String>, Vec<String>) {
    let prefix = if dir.is_empty() {
        String::new()
    } else {
        format!("{dir}/")
    };
    let mut dirs = BTreeSet::new();
    let mut files = BTreeSet::new();
    for file in tree {
        let Some(rest) = file.strip_prefix(prefix.as_str()) else {
            continue;
        };
        match rest.split_once('/') {
            Some((head, _)) => {
                dirs.insert(format!("{prefix}{head}"));
            }
            None => {
                files.insert((*file).to_owned());
            }
        }
    }
    (dirs.into_iter().collect(), files.into_iter().collect())
}

/// Walks the probe tree the way a real tree walk does: parent first, pruning
/// wherever the filter declines to descend, and asking about each child with its
/// parent's state in hand.
///
/// This exercises both entry points together, which is the only way the answers
/// mean anything: descent decides what is ever asked about, and the state
/// carried down decides the answer.
fn walk_tree(filter: &FilterInstance, tree: &[&str]) -> BTreeSet<String> {
    let mut included = BTreeSet::new();
    let mut stack = vec![(String::new(), FilterState::ROOT)];
    while let Some((dir, state)) = stack.pop() {
        let (subdirs, files) = children(tree, &dir);
        for file in files {
            if !filter
                .child_exclusion_state(state, &path(&file), false)
                .excluded()
            {
                included.insert(file);
            }
        }
        for subdir in subdirs {
            let child = path(&subdir);
            let next = filter.child_exclusion_state(state, &child, true);
            if filter.should_descend(next, &child) {
                stack.push((subdir, next));
            }
        }
    }
    included
}

/// Directories holding something included, which is what "should this directory
/// be in the merkle tree" means and how the ground truth derives its own
/// directory answers.
fn dirs_with_content(files: &BTreeSet<String>) -> BTreeSet<String> {
    DIRS.iter()
        .filter(|dir| files.iter().any(|f| f.starts_with(&format!("{dir}/"))))
        .map(|d| (*d).to_owned())
        .collect()
}

/// Decodes a ground-truth bitmask into the set of files git left included.
fn expected(mask: u32) -> BTreeSet<String> {
    FILES
        .iter()
        .enumerate()
        .filter(|(i, _)| mask & (1 << i) != 0)
        .map(|(_, f)| (*f).to_owned())
        .collect()
}

/// Every ancestor directory of `path`, root-most first.
fn ancestors(path: &str) -> Vec<&str> {
    path.char_indices()
        .filter(|(_, c)| *c == '/')
        .map(|(i, _)| &path[..i])
        .collect()
}

/// Whether `file` sits at or under a path-form re-inclusion in `patterns`.
///
/// This is lore's subtree-coverage deviation stated as a predicate: an anchored
/// re-inclusion covers its own subtree, so `!d/e` reaches `d/e/a`. Git's `!d/e`
/// matches the single path `d/e` and nothing under it.
fn covered_by_a_path_inclusion(patterns: &[&str], file: &str) -> bool {
    patterns.iter().any(|pattern| {
        let Some(rest) = pattern.strip_prefix('!') else {
            return false;
        };
        // Anchored exactly as `FilterInstance::compile` decides it: a leading
        // separator, or one inside. A name rule covers nothing below itself, by
        // design, so it never explains an extra path.
        let anchored = rest.starts_with('/') || rest.trim_matches('/').contains('/');
        if !anchored {
            return false;
        }
        let glob = rest.trim_matches('/');
        glob_match::glob_match(glob, file) || glob_match::glob_match(&format!("{glob}/**"), file)
    })
}

/// Whether git had nothing included below some ancestor of `file`, i.e. git
/// pruned there and lore descended instead.
fn below_a_pruned_ancestor(git_dirs: &BTreeSet<String>, file: &str) -> bool {
    ancestors(file)
        .iter()
        .any(|a| DIRS.contains(a) && !git_dirs.contains(*a))
}

/// Lore matches git on every one of the generated cases, except where it
/// includes more because a re-inclusion reaches below a directory git pruned.
///
/// Ground truth: git. See the module header.
///
/// The two assertions at the end are what make the deviation a bounded one
/// rather than an excuse. Lore must never drop a path git keeps, and it may only
/// keep extra paths when the pattern set holds a re-inclusion *and* git had
/// excluded an ancestor of that path -- which is precisely "git pruned here and
/// lore did not".
#[test]
fn gitignore_conformance() {
    let mut matched = 0usize;
    let mut extended = 0usize;
    let mut refused = 0usize;
    let mut dropped = Vec::new();
    let mut unexplained = Vec::new();

    for case in CASES {
        let Some(filter) = build(case.patterns) else {
            refused += 1;
            continue;
        };
        let got = walk_tree(&filter, FILES);
        let want = expected(case.included);
        let git_dirs = dirs_with_content(&want);

        let missing: Vec<_> = want.difference(&got).cloned().collect();
        if !missing.is_empty() {
            dropped.push(format!(
                "[{}] {:?} drops {missing:?}",
                case.kind, case.patterns
            ));
            continue;
        }

        let extra: Vec<_> = got.difference(&want).cloned().collect();
        if extra.is_empty() {
            matched += 1;
            assert_eq!(
                dirs_with_content(&got),
                git_dirs,
                "directory content disagrees with git for {:?}",
                case.patterns
            );
            continue;
        }

        extended += 1;
        for file in &extra {
            if !covered_by_a_path_inclusion(case.patterns, file)
                && !below_a_pruned_ancestor(&git_dirs, file)
            {
                unexplained.push(format!(
                    "[{}] {:?} adds {file}, which is neither under a path \
                     re-inclusion nor below a directory git pruned",
                    case.kind, case.patterns
                ));
            }
        }
    }

    assert!(
        dropped.is_empty(),
        "lore must never exclude what git includes:\n{}",
        dropped.join("\n")
    );
    assert!(
        unexplained.is_empty(),
        "lore included more than git outside the documented deviation:\n{}",
        unexplained.join("\n")
    );
    // Pinned so that a change in the mix is reviewed rather than absorbed: a
    // case moving from `matched` to `extended` widens the deviation, and one
    // moving to `refused` silently stops being tested at all.
    assert_eq!(
        (matched, extended, refused, CASES.len()),
        (2971, 555, 170, 3696),
        "case mix changed; regenerate the ground truth and review"
    );
}

/// Lore refuses an inclusion that starts with `**` and names more than one
/// component, because no prefix bounds where it could match and a walk would
/// have to visit every excluded directory in the tree to find out.
///
/// `!**/name` is accepted: gitignore documents `**/foo` as "the same as pattern
/// `foo`", so it compiles to an ordinary name rule with no traversal cost.
#[test]
fn unanchored_multi_component_inclusion_is_refused() {
    let mut filter = FilterInstance::default();
    filter.add_exclusion("**").expect("exclude");

    assert!(filter.add_inclusion("**/a").is_ok(), "**/a is just a");
    assert!(filter.add_inclusion("**/e/a").is_err());
    assert!(filter.add_inclusion("**/e/*").is_err());
    assert!(filter.add_inclusion("**").is_err());
}

/// Matching ignores case, in the glob and in the path alike.
///
/// This is a deliberate departure from git, which is case-sensitive by default.
/// Lore serves case-insensitive filesystems, where a rule that matched only one
/// spelling of a name would let the same content in or out depending on how it
/// happened to be typed.
#[test]
fn matching_is_case_insensitive() {
    let mut filter = FilterInstance::default();
    filter.add_exclusion("Engine").expect("exclude");
    filter.add_exclusion("*.TMP").expect("exclude");
    filter.add_exclusion("Deep/Sub/").expect("exclude");

    for spelling in ["engine", "Engine", "ENGINE", "eNgInE"] {
        assert!(
            filter.excludes(&path(spelling), true),
            "{spelling} should be excluded"
        );
    }
    for spelling in ["x.tmp", "x.TMP", "X.Tmp"] {
        assert!(
            filter.excludes(&path(spelling), false),
            "{spelling} should be excluded"
        );
    }
    for spelling in ["deep/sub", "Deep/Sub", "DEEP/SUB"] {
        assert!(
            filter.excludes(&path(spelling), true),
            "{spelling} should be excluded"
        );
    }

    // Re-inclusion folds the same way, so a differently spelled rule still
    // reaches the content it names.
    let mut filter = FilterInstance::default();
    filter.add_exclusion("**").expect("exclude");
    filter.add_inclusion("Engine/Content").expect("include");
    assert!(!filter.excludes(&path("engine/content/A.UAsset"), false));
    assert!(!filter.excludes(&path("ENGINE/CONTENT/a.uasset"), false));
}

/// A `**` followed by a wildcard component excludes what git excludes.
///
/// Ground truth: git. Upstream glob-match 0.2.1 gets these wrong -- it commits
/// the `**` backtrack point on the first literal match and cannot restore it, so
/// `**/*b` matched `x/b` but not `b/b`, and `**/*/a` matched `x/y/a` but not
/// `d/a`. Whether it failed depended on whether an earlier component happened to
/// match the tail pattern, which made it silent.
///
/// The filter under-excluded as a result: `**/*/a` left `d/a` in the tree. That
/// showed up in [`gitignore_conformance`] and nowhere else, which is the reason
/// the conformance table is generated combinatorially rather than hand-picked.
///
/// Fixed in `vendor/glob-match`; see the `LORE` notes there and its
/// `tests/doublestar.rs`. This test is the filter-level guard.
#[test]
fn doublestar_followed_by_a_wildcard_component_excludes() {
    let mut filter = FilterInstance::default();
    filter.add_exclusion("**/*/a").expect("exclude");
    for excluded in ["d/a", "d/e/a", "d/e/f/a", "dd/a", "e/a"] {
        assert!(
            filter.excludes(&path(excluded), false),
            "{excluded} should be excluded by **/*/a"
        );
    }
    // A single component has no `*/` to match, so it stays in.
    assert!(!filter.excludes(&path("a"), false));

    let mut filter = FilterInstance::default();
    filter.add_exclusion("a/**/*.tmp").expect("exclude");
    for excluded in ["a/x.tmp", "a/b/x.tmp", "a/x.tmp/y.tmp"] {
        assert!(
            filter.excludes(&path(excluded), false),
            "{excluded} should be excluded by a/**/*.tmp"
        );
    }
    assert!(!filter.excludes(&path("b/x.tmp"), false));
}

// ---------------------------------------------------------------------------
// Deep alternation, as named cases.
//
// The generated matrix already covers these shapes, but a failure there reports
// one line of a bitmask diff. These spell the same thing out at four levels,
// with a live sibling at every depth so a rule that over-reaches is visible.
// ---------------------------------------------------------------------------

/// The tree the alternation tests walk: four nested levels, a file at each, a
/// sibling directory at each, and an unrelated top-level branch.
const NESTED: &[&str] = &[
    "top.f",
    "other/f",
    "l1/f",
    "l1/sib/f",
    "l1/l2/f",
    "l1/l2/sib/f",
    "l1/l2/l3/f",
    "l1/l2/l3/sib/f",
    "l1/l2/l3/l4/f",
    "l1/l2/l3/l4/deeper/f",
];

fn nested_walk(patterns: &[&str]) -> BTreeSet<String> {
    let filter = build(patterns).expect("filter builds");
    walk_tree(&filter, NESTED)
}

fn set(files: &[&str]) -> BTreeSet<String> {
    files.iter().map(|f| (*f).to_owned()).collect()
}

/// Exclude / re-include alternating over four levels, each level's directory
/// re-included before the next exclusion.
///
/// Ground truth from git. With this `.gitignore`, `git status` reports exactly
/// `l1/l2/l3/l4/f` and `l1/l2/l3/l4/deeper/f` as untracked; every file at a
/// shallower level and every sibling is ignored. Note the last level has no
/// `/l1/l2/l3/l4/*` exclusion, so the re-inclusion carries the whole subtree --
/// which is why `deeper/f` comes back too.
#[test]
fn alternation_over_four_levels() {
    assert_eq!(
        nested_walk(&[
            "/*",
            "!/l1",
            "/l1/*",
            "!/l1/l2",
            "/l1/l2/*",
            "!/l1/l2/l3",
            "/l1/l2/l3/*",
            "!/l1/l2/l3/l4",
        ]),
        set(&["l1/l2/l3/l4/f", "l1/l2/l3/l4/deeper/f"])
    );
}

/// The same alternation written with directory-only rules.
///
/// Ground truth from git: `l1/l2/l3/f`, `l1/l2/l3/sib/f`, `l1/l2/l3/l4/f` and
/// `l1/l2/l3/l4/deeper/f` are untracked. The chain stops one level earlier than
/// above, so everything below `l1/l2/l3` is in -- including its sibling
/// directory, since nothing excludes one level down from there.
#[test]
fn alternation_over_four_levels_with_directory_rules() {
    assert_eq!(
        nested_walk(&[
            "/*",
            "!/l1/",
            "/l1/*",
            "!/l1/l2/",
            "/l1/l2/*",
            "!/l1/l2/l3/"
        ]),
        set(&[
            "l1/l2/l3/f",
            "l1/l2/l3/l4/f",
            "l1/l2/l3/l4/deeper/f",
            "l1/l2/l3/sib/f",
        ])
    );
}

/// An unanchored rule keeps applying inside a re-included subtree.
///
/// Ground truth from git: `l1/l2/f`, `l1/l2/l3/f`, `l1/l2/l3/l4/f` and
/// `l1/l2/l3/l4/deeper/f` are untracked; every `sib` directory is ignored at
/// every depth.
///
/// This is the case that rules out narrowing the line scan to "rules after the
/// one that re-included the parent": the bare `sib` sits *before* the
/// re-inclusion in the file, and must still bite below it.
#[test]
fn unanchored_rule_still_applies_inside_a_reincluded_subtree() {
    assert_eq!(
        nested_walk(&["/*", "!/l1", "/l1/*", "!/l1/l2", "sib"]),
        set(&[
            "l1/l2/f",
            "l1/l2/l3/f",
            "l1/l2/l3/l4/f",
            "l1/l2/l3/l4/deeper/f",
        ])
    );
}

/// Re-excluding a level cuts the branch, and a deeper re-inclusion reaches back
/// into it -- one of lore's two deviations from git.
///
/// Ground truth from git: **nothing** is untracked. `/l1/l2` re-excludes the
/// directory after `!/l1/l2` re-included it, git prunes there, and its
/// documentation states that `!/l1/l2/l3` cannot then re-include anything below.
///
/// Lore descends instead, so `l1/l2/l3` and its subtree come back. The ancestors
/// stay excluded either way, which is what keeps `l1/l2/f` and the siblings out.
#[test]
fn reexcluded_level_is_reentered_by_a_deeper_reinclusion() {
    let patterns = ["/*", "!/l1", "/l1/*", "!/l1/l2", "/l1/l2", "!/l1/l2/l3"];
    assert_eq!(
        nested_walk(&patterns),
        set(&[
            "l1/l2/l3/f",
            "l1/l2/l3/l4/f",
            "l1/l2/l3/l4/deeper/f",
            "l1/l2/l3/sib/f",
        ])
    );

    // The cut directory itself stays excluded; only its re-included descendant
    // comes back.
    let filter = build(&patterns).expect("filter builds");
    assert!(filter.excludes(&path("l1/l2"), true));
    assert!(!filter.excludes(&path("l1/l2/l3"), true));

    // And the walk only looks inside it because something below is re-included.
    let state = filter.exclusion_state(&path("l1/l2"), true);
    assert!(filter.should_descend(state, &path("l1/l2")));
}

/// A directory excluded with nothing re-included below it is not descended, so
/// `excludes_subtree` can answer for the whole subtree at once.
#[test]
fn excluded_subtree_with_no_reinclusion_is_not_descended() {
    let filter = build(&["/*", "!/l1", "/l1/*", "!/l1/l2"]).expect("filter builds");

    // `l1/sib` is excluded and holds no re-inclusion.
    let sib = path("l1/sib");
    let state = filter.exclusion_state(&sib, true);
    assert!(state.excluded());
    assert!(!filter.should_descend(state, &sib));
    assert!(filter.excludes_subtree(&sib));

    // `l1` is excluded by `/*` but leads to the re-inclusion, so it is descended
    // and its subtree cannot be dismissed wholesale.
    let l1 = path("l1");
    assert!(filter.should_descend(filter.exclusion_state(&l1, true), &l1));
    assert!(!filter.excludes_subtree(&l1));
}

/// The ancestor memo changes no answer.
///
/// `Filter::excludes` folds a path's parent once per directory and caches it, so
/// a batch of paths sharing ancestors -- a targets file naming hundreds of
/// thousands of them -- pays for each directory once. `FilterInstance::excludes`
/// folds every path from the root with no cache. The two must agree on every
/// path of every case in the ground-truth table, or the cache is a bug.
#[test]
fn the_ancestor_memo_changes_no_answer() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    let mut compared = 0usize;
    for case in CASES {
        let Some(instance) = build(case.patterns) else {
            continue;
        };
        let mut filter = Filter::default();
        for pattern in case.patterns {
            let outcome = match pattern.strip_prefix('!') {
                Some(rest) => filter.ignore.add_inclusion(rest),
                None => filter.ignore.add_exclusion(pattern),
            };
            outcome.expect("the instance above accepted the same rules");
        }

        // Ask twice, so the second call is answered from a populated memo and
        // the first is not.
        for _ in 0..2 {
            for (probe, is_dir) in FILES
                .iter()
                .map(|f| (*f, false))
                .chain(DIRS.iter().map(|d| (*d, true)))
            {
                let path = path(probe);
                assert_eq!(
                    filter.excludes(&path, is_dir, FilterMode::Ignore),
                    instance.excludes(&path, is_dir),
                    "memo disagrees on {probe} for {:?}",
                    case.patterns
                );
                compared += 1;
            }
        }
    }
    assert!(
        compared > 100_000,
        "expected a broad comparison, got {compared}"
    );
}

/// Adding rules to a filter that has already answered empties the ancestor memo.
///
/// The slot fields are public and [`FilterInstance::add_exclusion`] takes
/// `&mut self`, so a caller can load a filter, query it, and then add to it. A
/// cached ancestor verdict from before the addition would answer with rules that
/// no longer describe the filter.
#[test]
fn adding_rules_after_a_query_invalidates_the_memo() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    let mut filter = Filter::default();
    filter.ignore.add_exclusion("/a/b/c").expect("exclude");

    // Caches the verdict for `a/b`.
    assert!(filter.excludes(&path("a/b/c"), false, FilterMode::Ignore));
    assert!(!filter.excludes(&path("a/b/other"), false, FilterMode::Ignore));

    filter.ignore.add_exclusion("/a/b").expect("exclude");
    assert!(filter.excludes(&path("a/b/other"), false, FilterMode::Ignore));

    // And the other direction: a re-inclusion added later must take effect.
    filter.ignore.add_inclusion("/a/b/keep").expect("include");
    assert!(!filter.excludes(&path("a/b/keep"), false, FilterMode::Ignore));
}

/// A path has to clear both slots, and neither slot's rules leak into the other.
///
/// The ignore and view filters are folded together but decided separately: a view
/// re-inclusion cannot recover ignore-excluded content, and `FilterMode` selects
/// which slots are consulted at all.
#[test]
fn the_two_slots_are_independent_and_both_must_pass() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    let mut filter = Filter::default();
    filter.ignore.add_exclusion("*.tmp").expect("exclude");
    filter.view.add_exclusion("**").expect("exclude");
    filter
        .view
        .add_inclusion("engine/content")
        .expect("include");

    // In view and not ignored.
    let kept = path("engine/content/asset.uasset");
    assert!(!filter.excludes(&kept, false, FilterMode::Full));
    assert!(!filter.excludes(&kept, false, FilterMode::Ignore));
    assert!(!filter.excludes(&kept, false, FilterMode::View));

    // In view, but the ignore slot excludes it. A view re-inclusion does not
    // recover it.
    let ignored = path("engine/content/scratch.tmp");
    assert!(filter.excludes(&ignored, false, FilterMode::Full));
    assert!(filter.excludes(&ignored, false, FilterMode::Ignore));
    assert!(!filter.excludes(&ignored, false, FilterMode::View));

    // Not ignored, but out of view.
    let unseen = path("game/content/asset.uasset");
    assert!(filter.excludes(&unseen, false, FilterMode::Full));
    assert!(!filter.excludes(&unseen, false, FilterMode::Ignore));
    assert!(filter.excludes(&unseen, false, FilterMode::View));

    // Descent is per slot: the view slot must be allowed to reach
    // `engine/content`, and neither slot has anything to find under `game`.
    let states = FilterStates::ROOT;
    let engine = path("engine");
    let (engine_states, _) = filter.child_exclusion_states(states, &engine, true, FilterMode::Full);
    assert!(filter.should_descend(engine_states, &engine, FilterMode::Full));

    let game = path("game");
    let (game_states, _) = filter.child_exclusion_states(states, &game, true, FilterMode::Full);
    assert!(!filter.should_descend(game_states, &game, FilterMode::Full));
}

/// `excludes_tree` keeps a directory a walk has to descend into.
///
/// This is the verdict a tree walk needs, and `excludes` is not it: with `**`
/// and `!included/**` the `included` directory matches only the blanket
/// exclusion, so `excludes` reports it excluded -- yet everything under it is in
/// view, and a sparse working tree cannot hold those files without the
/// directory. Pruning a walk on the node verdict strands the whole subtree.
#[test]
fn the_walk_verdict_keeps_a_directory_it_must_descend_into() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    let mut filter = Filter::default();
    filter.view.add_exclusion("**").expect("exclude");
    filter.view.add_inclusion("included/**").expect("include");

    let included = path("included");
    assert!(filter.excludes(&included, true, FilterMode::View));
    assert!(!filter.excludes_tree(&included, true, FilterMode::View));
    assert!(!filter.excludes_tree(&path("included/a.txt"), false, FilterMode::View));

    // A sibling with nothing re-included below it is dropped whole.
    let excluded = path("excluded");
    assert!(filter.excludes(&excluded, true, FilterMode::View));
    assert!(filter.excludes_tree(&excluded, true, FilterMode::View));

    // A file answers the same to both, having no subtree to answer for.
    let dropped = path("excluded/x.txt");
    assert!(filter.excludes(&dropped, false, FilterMode::View));
    assert!(filter.excludes_tree(&dropped, false, FilterMode::View));
}

/// The two shapes a walk can take reach the same files.
///
/// A walk that holds its parent's [`FilterStates`] steps them with
/// `child_excludes_tree`; one handed a path with no walk behind it -- a change
/// list, a clone dependency, a path named on the command line -- asks
/// `excludes_tree` for the whole path. Both have to agree with [`walk_tree`] on
/// every case in the ground-truth table, or the same tree yields different
/// content depending on how it was reached.
#[test]
fn the_whole_path_walk_reaches_the_same_files_as_the_stepped_walk() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    fn walk_whole_paths(filter: &Filter, tree: &[&str]) -> BTreeSet<String> {
        let mut included = BTreeSet::new();
        let mut stack = vec![String::new()];
        while let Some(dir) = stack.pop() {
            let (subdirs, files) = children(tree, &dir);
            for file in files {
                if !filter.excludes_tree(&path(&file), false, FilterMode::Ignore) {
                    included.insert(file);
                }
            }
            for subdir in subdirs {
                if !filter.excludes_tree(&path(&subdir), true, FilterMode::Ignore) {
                    stack.push(subdir);
                }
            }
        }
        included
    }

    fn walk_threaded(filter: &Filter, tree: &[&str]) -> BTreeSet<String> {
        let mut included = BTreeSet::new();
        let mut stack = vec![(String::new(), FilterStates::ROOT)];
        while let Some((dir, states)) = stack.pop() {
            let (subdirs, files) = children(tree, &dir);
            for file in files {
                let (_, excluded) =
                    filter.child_excludes_tree(states, &path(&file), false, FilterMode::Ignore);
                if !excluded {
                    included.insert(file);
                }
            }
            for subdir in subdirs {
                let (child, excluded) =
                    filter.child_excludes_tree(states, &path(&subdir), true, FilterMode::Ignore);
                if !excluded {
                    stack.push((subdir, child));
                }
            }
        }
        included
    }

    let mut compared = 0usize;
    for case in CASES {
        let Some(instance) = build(case.patterns) else {
            continue;
        };
        let mut filter = Filter::default();
        for pattern in case.patterns {
            let outcome = match pattern.strip_prefix('!') {
                Some(rest) => filter.ignore.add_inclusion(rest),
                None => filter.ignore.add_exclusion(pattern),
            };
            outcome.expect("the instance above accepted the same rules");
        }
        let stepped = walk_tree(&instance, FILES);
        assert_eq!(
            walk_whole_paths(&filter, FILES),
            stepped,
            "the whole-path walk and the stepped walk disagree for {:?}",
            case.patterns
        );
        assert_eq!(
            walk_threaded(&filter, FILES),
            stepped,
            "the threaded walk and the stepped walk disagree for {:?}",
            case.patterns
        );
        compared += 1;
    }
    assert!(
        compared > 3_000,
        "expected a broad comparison, got {compared}"
    );
}

/// A walk that starts partway down the tree sees what a walk from the root sees
/// there.
///
/// Every walk entry point that is handed a subdirectory seeds itself with
/// `exclusion_states` (or `parent_exclusion_states` where the first step is the
/// path itself) rather than with [`FilterStates::ROOT`]. If that seed differed
/// from what the root walk reached, `lore status <dir>` would filter its subtree
/// differently from `lore status`.
#[test]
fn a_walk_seeded_partway_down_matches_one_from_the_root() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    /// Every directory's states, as reached by stepping down from the root.
    fn stepped_states(
        filter: &Filter,
        tree: &[&str],
    ) -> std::collections::BTreeMap<String, FilterStates> {
        let mut reached = std::collections::BTreeMap::new();
        let mut stack = vec![(String::new(), FilterStates::ROOT)];
        while let Some((dir, states)) = stack.pop() {
            let (subdirs, _) = children(tree, &dir);
            for subdir in subdirs {
                let child = path(&subdir);
                let (child_states, excluded) =
                    filter.child_excludes_tree(states, &child, true, FilterMode::Ignore);
                reached.insert(subdir.clone(), child_states);
                if !excluded {
                    stack.push((subdir, child_states));
                }
            }
        }
        reached
    }

    let mut compared = 0usize;
    for case in CASES {
        if build(case.patterns).is_none() {
            continue;
        }
        let mut filter = Filter::default();
        for pattern in case.patterns {
            let outcome = match pattern.strip_prefix('!') {
                Some(rest) => filter.ignore.add_inclusion(rest),
                None => filter.ignore.add_exclusion(pattern),
            };
            outcome.expect("build accepted the same rules");
        }

        for (dir, walked) in stepped_states(&filter, FILES) {
            let directory = path(&dir);
            // The seed a walk rooted at `dir` uses for its children.
            let seeded = filter.exclusion_states(&directory);
            // The seed a recursion that asks about `dir` itself uses, stepped
            // the one component it is about to ask about.
            let (from_parent, _) = filter.child_excludes_tree(
                filter.parent_exclusion_states(&directory),
                &directory,
                true,
                FilterMode::Ignore,
            );

            let (_, walked_excludes) = filter.child_excludes_tree(
                walked,
                &path(&format!("{dir}/probe")),
                false,
                FilterMode::Ignore,
            );
            for (label, seed) in [("exclusion_states", seeded), ("parent step", from_parent)] {
                let (_, seed_excludes) = filter.child_excludes_tree(
                    seed,
                    &path(&format!("{dir}/probe")),
                    false,
                    FilterMode::Ignore,
                );
                assert_eq!(
                    seed_excludes, walked_excludes,
                    "{label} at {dir} disagrees with the walk for {:?}",
                    case.patterns
                );
                assert_eq!(
                    filter.should_descend(seed, &directory, FilterMode::Ignore),
                    filter.should_descend(walked, &directory, FilterMode::Ignore),
                    "{label} descent at {dir} disagrees with the walk for {:?}",
                    case.patterns
                );
            }
            compared += 1;
        }
    }
    assert!(
        compared > 10_000,
        "expected a broad comparison, got {compared}"
    );
}

/// A threaded walk answers for both slots the way a whole-path query does.
///
/// The equivalence tests above run one slot, where a verdict cannot be reached
/// by the other. This puts rules in both and holds the threaded walk against
/// `excludes_tree`, which is the shape `FilterMode::Full` operations -- stage,
/// reset, unstage, dirty -- ask in.
#[test]
fn a_threaded_walk_agrees_with_a_whole_path_query_across_both_slots() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    let mut compared = 0usize;
    for ignore_case in CASES {
        let Some(_) = build(ignore_case.patterns) else {
            continue;
        };
        for view_case in CASES.iter().rev().take(8) {
            let Some(_) = build(view_case.patterns) else {
                continue;
            };
            let mut filter = Filter::default();
            for pattern in ignore_case.patterns {
                let outcome = match pattern.strip_prefix('!') {
                    Some(rest) => filter.ignore.add_inclusion(rest),
                    None => filter.ignore.add_exclusion(pattern),
                };
                outcome.expect("build accepted the same rules");
            }
            for pattern in view_case.patterns {
                let outcome = match pattern.strip_prefix('!') {
                    Some(rest) => filter.view.add_inclusion(rest),
                    None => filter.view.add_exclusion(pattern),
                };
                outcome.expect("build accepted the same rules");
            }

            let mut stack = vec![(String::new(), FilterStates::ROOT)];
            while let Some((dir, states)) = stack.pop() {
                let (subdirs, files) = children(FILES, &dir);
                for file in files {
                    let file_path = path(&file);
                    let (_, threaded) =
                        filter.child_excludes_tree(states, &file_path, false, FilterMode::Full);
                    assert_eq!(
                        threaded,
                        filter.excludes_tree(&file_path, false, FilterMode::Full),
                        "file {file} disagrees for ignore {:?} view {:?}",
                        ignore_case.patterns,
                        view_case.patterns
                    );
                    compared += 1;
                }
                for subdir in subdirs {
                    let dir_path = path(&subdir);
                    let (child, threaded) =
                        filter.child_excludes_tree(states, &dir_path, true, FilterMode::Full);
                    assert_eq!(
                        threaded,
                        filter.excludes_tree(&dir_path, true, FilterMode::Full),
                        "directory {subdir} disagrees for ignore {:?} view {:?}",
                        ignore_case.patterns,
                        view_case.patterns
                    );
                    compared += 1;
                    if !threaded {
                        stack.push((subdir, child));
                    }
                }
            }
        }
    }
    assert!(
        compared > 10_000,
        "expected a broad comparison, got {compared}"
    );
}

/// A forced walk is answered without consulting the filter.
///
/// `--force` drops nothing, so it must report nothing excluded and emit no
/// event. It also reads no verdict -- every step below a forced one is forced
/// too -- so the state handed back is [`FilterStates::ROOT`] rather than one the
/// walk would have paid a line scan to produce.
#[test]
fn a_forced_step_excludes_nothing_and_carries_no_verdict() {
    use lore_revision::filter::Filter;
    use lore_revision::filter::FilterMode;

    let mut filter = Filter::default();
    filter
        .ignore
        .add_exclusion("intermediate")
        .expect("exclusion");
    filter.view.add_exclusion("binaries").expect("exclusion");

    for (name, is_directory) in [
        ("intermediate", true),
        ("binaries", true),
        ("keep.txt", false),
    ] {
        let subject = path(name);
        // The unforced control asks the non-emitting query: emitting needs a
        // task-local execution context this test has no other use for.
        let (unforced_states, unforced) = filter.child_excludes_tree(
            FilterStates::ROOT,
            &subject,
            is_directory,
            FilterMode::Full,
        );
        let (forced_states, forced) = filter.child_emit_excludes_unless_forced(
            true,
            FilterStates::ROOT,
            &subject,
            is_directory,
            FilterMode::Full,
        );
        assert!(
            !forced,
            "a forced step excludes nothing, {name} was dropped"
        );
        assert_eq!(
            forced_states,
            FilterStates::ROOT,
            "a forced step carries no verdict, {name} returned one"
        );
        let (tree_states, tree) = filter.child_excludes_tree_unless_forced(
            true,
            FilterStates::ROOT,
            &subject,
            is_directory,
            FilterMode::Full,
        );
        assert!(!tree, "a forced step excludes nothing, {name} was dropped");
        assert_eq!(tree_states, FilterStates::ROOT);
        // The rules do bite when the walk is not forced, or the assertions above
        // would hold for a filter that excludes nothing.
        if name != "keep.txt" {
            assert!(unforced, "{name} should be excluded when not forced");
            assert_ne!(unforced_states, FilterStates::ROOT);
        }
    }
}

/// `save` writes back rules that load to the same filter, and leaves out the
/// companions `add_inclusion` generates.
#[tokio::test]
#[allow(clippy::disallowed_methods)] // Test fixture writes; not subject to repository write-token discipline.
async fn saved_rules_reload_to_the_same_filter() {
    let authored = [
        "/Intermediate",
        "*.tmp",
        "Binaries/",
        "engine/content",
        "!engine/content/keep",
        "**/node_modules",
    ];
    let mut original = FilterInstance::default();
    for rule in authored {
        match rule.strip_prefix('!') {
            Some(rest) => original.add_inclusion(rest).expect("include"),
            None => original.add_exclusion(rule).expect("exclude"),
        }
    }

    let dir = lore_base::test_util::TempDir::new("lore-filter-save-roundtrip-");
    let file = dir.child("filter");
    lore_revision::filter::save(&original, &file)
        .await
        .expect("save");
    let reloaded = lore_revision::filter::load_filter(&file).expect("load");

    assert_eq!(reloaded.lines.len(), original.lines.len());
    for case in CASES.iter().take(200) {
        for probe in FILES {
            let probe = path(probe);
            assert_eq!(
                reloaded.excludes(&probe, false),
                original.excludes(&probe, false),
                "round trip changed the verdict for {} ({:?})",
                probe.as_str(),
                case.patterns
            );
        }
    }
}

/// Folding a whole path and stepping down it one component at a time reach the
/// same verdict.
///
/// The two entry points answer the same question by different routes:
/// `exclusion_state` folds a path that arrives whole, `child_exclusion_state`
/// takes one step given the parent's verdict. A walk uses the second and every
/// other caller the first, so a divergence would make the tree disagree with the
/// paths named on the command line.
#[test]
fn folding_a_path_and_stepping_down_it_agree() {
    let mut compared = 0usize;
    for case in CASES {
        let Some(filter) = build(case.patterns) else {
            continue;
        };
        for (probe, is_dir) in FILES
            .iter()
            .map(|f| (*f, false))
            .chain(DIRS.iter().map(|d| (*d, true)))
        {
            let mut stepped = FilterState::ROOT;
            let mut walked = String::new();
            let mut components = probe.split('/').peekable();
            while let Some(component) = components.next() {
                if !walked.is_empty() {
                    walked.push('/');
                }
                walked.push_str(component);
                let last = components.peek().is_none();
                stepped = filter.child_exclusion_state(stepped, &path(&walked), !last || is_dir);
            }
            assert_eq!(
                stepped,
                filter.exclusion_state(&path(probe), is_dir),
                "fold and step disagree on {probe} for {:?}",
                case.patterns
            );
            compared += 1;
        }
    }
    assert!(
        compared > 50_000,
        "expected a broad comparison, got {compared}"
    );
}
