// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT
//! The [`Internal`] error type for non-handleable errors.
//!
//! `Internal` is a pure data type wrapping an arbitrary error source. It
//! serves as the catch-all variant in every error set for errors that
//! callers cannot meaningfully handle.
//!
//! Trace storage and human "what was being attempted" context strings live
//! on the wrapping [`crate::Traced`] instance held by the generated enum's
//! `Internal(Traced<Internal>)` variant — see [`crate::Location`]'s
//! `with_context` constructor. `Internal` itself carries only the boxed
//! source error.

use std::error::Error;
use std::fmt;
use std::sync::Arc;

use crate::location::Location;
use crate::traced::Trace;
use crate::traced::Traced;

/// An opaque internal error wrapping an arbitrary error source.
///
/// Every error set generated by `#[error_set]` includes an
/// `Internal(Traced<Internal>)` variant using this type. When an error does
/// not match any handleable variant during cross-set mapping, it is wrapped
/// in `Internal` and lifted into a `Traced<>` wrapper that carries both the
/// trace and any context strings attached at hop sites.
///
/// The original error is preserved as [`Error::source()`] for debugging and
/// logging.
#[derive(Clone)]
pub struct Internal {
    source: Arc<dyn Error + Send + Sync + 'static>,
}

/// A simple string-based error for use as `Internal`'s source when there is
/// no underlying cause.
#[derive(Debug)]
struct StringError(String);

impl fmt::Display for StringError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl Error for StringError {}

impl Internal {
    /// FFI error code for internal errors.
    pub const FFI_CODE: i32 = -1;

    /// Creates an `Internal` error from a message string with no underlying
    /// cause.
    ///
    /// Use this when an operation fails but there is no source error to wrap —
    /// for example, an unsupported code path or a precondition violation.
    ///
    /// ```
    /// # use lore_error_set::Internal;
    /// let err = Internal::msg("store does not support operation");
    /// assert_eq!(err.to_string(), "store does not support operation");
    /// ```
    pub fn msg(message: impl Into<String>) -> Self {
        let message = message.into();
        Self {
            source: Arc::new(StringError(message)),
        }
    }

    /// Creates a new `Internal` error wrapping the given source.
    pub fn new(source: Arc<dyn Error + Send + Sync + 'static>) -> Self {
        Self { source }
    }
}

impl fmt::Debug for Internal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Internal")
            .field("source", &self.source)
            .finish()
    }
}

impl fmt::Display for Internal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.source, f)
    }
}

impl Error for Internal {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Some(&*self.source)
    }
}

/// Lifts a bare `Internal` into a `Traced<Internal>`, capturing the caller
/// location as the first trace entry.
///
/// Enables `Err(Internal::msg("...").into())` from a function returning
/// `Result<_, Traced<Internal>>`.
impl From<Internal> for Traced<Internal> {
    #[track_caller]
    fn from(internal: Internal) -> Self {
        let caller = std::panic::Location::caller();
        let mut trace = Trace::new();
        trace.push(Location::new(caller.file(), caller.line(), caller.column()));
        Traced::new(internal, trace)
    }
}

/// Trait implemented by error types that are able to create an `Internal` variant.
pub trait SupportsInternalError {
    /// Creates an `Internal` variant from a message string.
    fn internal(msg: impl Into<String>) -> Self;

    /// Creates an `Internal` variant wrapping a source error with a
    /// context string. The context is recorded on the resulting trace as a
    /// `Location::with_context` entry at the caller's location.
    fn internal_with_context(
        source: impl ::std::error::Error + Send + Sync + 'static,
        context: &str,
    ) -> Self;
}

// ---------------------------------------------------------------------------
// Send + Sync assertions
// ---------------------------------------------------------------------------
fn _assert_internal_send_sync() {
    fn _assert<T: Send + Sync>() {}
    _assert::<Internal>();
}
