// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT
//! The [`ErrorSet`] trait and [`TracedBox`] type for cross-set error mapping.
//!
//! [`ErrorSet`] is the core trait implemented by every error set generated by
//! `#[error_set]`. It provides the runtime downcasting mechanism for mapping
//! errors between different error sets.
//!
//! [`TracedBox`] is an intermediate representation that carries a boxed error
//! together with its trace, used during cross-set mapping.

use std::error::Error;
use std::fmt;

use crate::internal::Internal;
use crate::traced::Trace;
use crate::traced::Traced;

/// An intermediate representation carrying a type-erased error and its trace.
///
/// Used during cross-set error mapping: the source error set extracts its
/// inner error into a `TracedBox`, and the target error set attempts to
/// downcast it back to a concrete type.
pub struct TracedBox {
    /// The type-erased inner error.
    pub inner: Box<dyn Error + Send + Sync + 'static>,
    /// The accumulated trace from the error's lifetime.
    pub trace: Trace,
}

impl TracedBox {
    /// Creates a new `TracedBox` from an inner error and trace.
    pub fn new(inner: Box<dyn Error + Send + Sync + 'static>, trace: Trace) -> Self {
        Self { inner, trace }
    }

    /// Creates a `TracedBox` from a `Traced<E>` where `E` is a concrete error
    /// type.
    ///
    /// This boxes the inner error for type-erased storage and preserves the
    /// trace.
    pub fn from_traced<E>(traced: Traced<E>) -> Self
    where
        E: Error + Send + Sync + 'static,
    {
        let (inner, trace) = traced.into_parts();
        Self {
            inner: Box::new(inner),
            trace,
        }
    }
}

impl fmt::Debug for TracedBox {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("TracedBox")
            .field("inner", &self.inner)
            .field("trace", &self.trace)
            .finish()
    }
}

impl fmt::Display for TracedBox {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.inner, f)
    }
}

// ---------------------------------------------------------------------------
// Send + Sync assertions
// ---------------------------------------------------------------------------
fn _assert_traced_box_send_sync() {
    fn _assert<T: Send + Sync>() {}
    _assert::<TracedBox>();
}

// ---------------------------------------------------------------------------
// ErrorSet trait
// ---------------------------------------------------------------------------

/// Trait for error sets that support cross-set mapping.
///
/// This trait is generated by the `#[error_set]` macro for each error set
/// enum. It provides the runtime downcasting mechanism for mapping errors
/// between different error sets.
///
/// # Contract
///
/// - [`extract_inner`](ErrorSet::extract_inner) extracts the inner error from
///   the set and packages it as a [`TracedBox`] for inspection.
/// - [`try_from_inner`](ErrorSet::try_from_inner) attempts to reconstruct the
///   error set from a `TracedBox` by downcasting. Returns `Ok(Self)` if the
///   inner type matches a variant, or `Err(TracedBox)` if no match is found.
/// - [`wrap_internal`](ErrorSet::wrap_internal) wraps an unmatched error as
///   the `Internal` variant with a context string.
/// - [`Variants`](ErrorSet::Variants) is the type-level [`variants`] list of
///   the set's declared inner types — consumed by [`HasAll`] to drive the
///   strict-forward bound.
pub trait ErrorSet: Error + Sized + Send + Sync + 'static {
    /// The per-error-set `Matched` type containing all handleable variants
    /// (no `Internal`, no `Ok`).
    type Matched;

    /// Type-level [`variants`] list of the inner types this error set
    /// declares (excluding [`Internal`](crate::Internal), which every set
    /// carries unconditionally). Auto-set by `#[error_set]`.
    type Variants;

    /// Converts this error set value into a `Matched` variant.
    ///
    /// Returns `Err(Traced<Internal>)` if the error is `Internal` (with
    /// context added; the trace from the upstream `Traced<Internal>` wrapper
    /// is preserved and extended with `caller`). Returns
    /// `Ok(Matched::Variant(traced))` for handleable variants.
    fn into_matched(
        self,
        context: &str,
        caller: crate::location::Location,
    ) -> Result<Self::Matched, Traced<Internal>>;

    /// Like [`into_matched`](ErrorSet::into_matched), but with a lazily
    /// evaluated context string. The closure is only called when the error
    /// is `Internal`.
    fn into_matched_with<F>(
        self,
        f: F,
        caller: crate::location::Location,
    ) -> Result<Self::Matched, Traced<Internal>>
    where
        F: FnOnce() -> String;

    /// Pushes a trace entry onto the error set value's trace.
    fn push_trace(&mut self, location: crate::location::Location);

    /// Extracts the inner error and trace for cross-set mapping.
    fn extract_inner(self) -> TracedBox;

    /// Attempts to construct `Self` from a [`TracedBox`] via downcasting.
    ///
    /// Returns `Ok(Self)` if the boxed error's concrete type matches one of
    /// this set's handleable variants. Returns `Err(TracedBox)` if no match
    /// is found, allowing the caller to wrap it as `Internal`.
    fn try_from_inner(inner: TracedBox) -> Result<Self, TracedBox>;

    /// Wraps an unmatched error as the `Internal` variant with a context
    /// string describing why the mapping occurred.
    fn wrap_internal(err: TracedBox, context: &str) -> Self;
}

// ---------------------------------------------------------------------------
// Has<V> marker trait — compile-time variant-presence witness
// ---------------------------------------------------------------------------

/// Marker trait asserting that an [`ErrorSet`] declares a variant whose inner
/// type is `V`.
///
/// The `#[error_set]` macro auto-implements `Has<V>` for every variant declared
/// on the set (plus [`Has<Internal>`](crate::Internal) universally — every set
/// always carries `Internal`). This lets per-source-set strict-forward methods
/// require, at the type level, that the target declares every variant the
/// source declares — turning a missing target variant into a compile error
/// instead of a silent runtime collapse to `Target::Internal`.
///
/// Use the strict `forward` generated alongside each `#[error_set]` to
/// propagate errors — the target must declare every variant the source
/// declares, which is what `Has<V>` enforces.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not declare a `{V}` variant",
    label = "missing variant",
    note = "the source error set declares `{V}`; add `{V}` to `{Self}` so .forward preserves it."
)]
pub trait Has<V>: ErrorSet {}

// ---------------------------------------------------------------------------
// Type-level variant list + HasAll — variadic-bound encoding for the strict
// forward.
// ---------------------------------------------------------------------------

/// Type-level cons list of inner-variant types — the encoding consumed by
/// [`ErrorSet::Variants`] and [`HasAll`].
///
/// Stable Rust has no variadic generics, so the strict forward expresses
/// "Target declares every variant of Source" by walking a cons list of the
/// source's variants and requiring `Target: Has<H>` at each link.
pub mod variants {
    use ::std::marker::PhantomData;

    /// One variant of an [`ErrorSet`](super::ErrorSet)'s variant list — head
    /// type `H`, tail list `T`.
    pub struct Cons<H, T>(PhantomData<(H, T)>);

    /// End of an [`ErrorSet`](super::ErrorSet)'s variant list.
    pub struct Nil;
}

/// Marker: an [`ErrorSet`] declares every variant in the type-level list
/// `List` (which should be a chain of [`variants::Cons`]es terminated by
/// [`variants::Nil`]).
///
/// The blanket impls walk `List` recursively, requiring `Self: Has<H>` at
/// each link. When a target is missing a variant, the recursion bottoms out
/// on a `Has<MissingV>` bound, and the `#[diagnostic::on_unimplemented]` on
/// [`Has`] surfaces the per-variant error message.
///
/// You should not implement this trait directly — the blanket impls cover
/// all valid cases.
#[diagnostic::on_unimplemented(
    message = "`{Self}` does not declare every variant of the source error set",
    label = "target missing a source variant",
    note = "strict .forward requires the target to declare every variant of the source; \
            see the `Has<…>` requirement below for the specific missing variant. Add the \
            variant to `{Self}` to preserve it."
)]
pub trait HasAll<List> {}

impl<S: ErrorSet> HasAll<variants::Nil> for S {}

impl<S, H, T> HasAll<variants::Cons<H, T>> for S where S: ErrorSet + Has<H> + HasAll<T> {}
